#!/bin/sh

if [ ! -d 'js/min/' ]; then mkdir js/min/; echo 'Successfully created directory js/min/'; fi
if [ ! -d 'js/min/viewmodels/' ]; then mkdir js/min/viewmodels/; echo 'Successfully created directory js/min/viewmodels/'; fi
if [ ! -d 'js/min/utils/' ]; then mkdir js/min/utils/; echo 'Successfully created directory js/min/utils/'; fi
if [ ! -d 'js/min/models/' ]; then mkdir js/min/models/; echo 'Successfully created directory js/min/models/'; fi
if [ ! -d 'js/min/models/cn/' ]; then mkdir js/min/models/cn/; echo 'Successfully created directory js/min/models/cn/'; fi
if [ ! -d 'js/min/models/en/' ]; then mkdir js/min/models/en/; echo 'Successfully created directory js/min/models/en/'; fi
if [ ! -d 'js/min/models/jp/' ]; then mkdir js/min/models/jp/; echo 'Successfully created directory js/min/models/jp/'; fi
if [ ! -d 'js/min/bootstrap/' ]; then mkdir js/min/bootstrap/; echo 'Successfully created directory js/min/bootstrap/'; fi
if [ ! -d 'js/min/bootstrap/jp/' ]; then mkdir js/min/bootstrap/jp/; echo 'Successfully created directory js/min/bootstrap/jp/'; fi
if [ ! -d 'js/min/bootstrap/en/' ]; then mkdir js/min/bootstrap/en/; echo 'Successfully created directory js/min/bootstrap/en/'; fi
if [ ! -d 'js/min/bootstrap/cn/' ]; then mkdir js/min/bootstrap/cn/; echo 'Successfully created directory js/min/bootstrap/cn/'; fi
if [ ! -d 'js/min/app/' ]; then mkdir js/min/app/; echo 'Successfully created directory js/min/app/'; fi
if [ ! -d 'js/min/app/jp/' ]; then mkdir js/min/app/jp/; echo 'Successfully created directory js/min/app/jp/'; fi
if [ ! -d 'js/min/app/en/' ]; then mkdir js/min/app/en/; echo 'Successfully created directory js/min/app/en/'; fi
if [ ! -d 'js/min/app/cn/' ]; then mkdir js/min/app/cn/; echo 'Successfully created directory js/min/app/cn/'; fi
if [ ! -d 'css/min/' ]; then mkdir css/min/; echo 'Successfully created directory css/min/'; fi

if [ '$(ls -A js/min/viewmodels/)' ]; then rm -f js/min/viewmodels/*; echo 'Removed all files from js/min/viewmodels/'; fi
if [ '$(ls -A js/min/utils/)' ]; then rm -f js/min/utils/*; echo 'Removed all files from js/min/utils/'; fi
if [ '$(ls -A js/min/models/cn/)' ]; then rm -f js/min/models/cn/*; echo 'Removed all files from js/min/models/cn/'; fi
if [ '$(ls -A js/min/models/en/)' ]; then rm -f js/min/models/en/*; echo 'Removed all files from js/min/models/en/'; fi
if [ '$(ls -A js/min/models/jp/)' ]; then rm -f js/min/models/jp/*; echo 'Removed all files from js/min/models/jp/'; fi
if [ '$(ls -A js/min/bootstrap/jp/)' ]; then rm -f js/min/bootstrap/jp/*; echo 'Removed all files from js/min/bootstrap/jp/'; fi
if [ '$(ls -A js/min/bootstrap/en/)' ]; then rm -f js/min/bootstrap/en/*; echo 'Removed all files from js/min/bootstrap/en/'; fi
if [ '$(ls -A js/min/bootstrap/cn/)' ]; then rm -f js/min/bootstrap/cn/*; echo 'Removed all files from js/min/bootstrap/cn/'; fi
if [ '$(ls -A js/min/app/jp/)' ]; then rm -f js/min/app/jp/*; echo 'Removed all files from js/min/app/jp/'; fi
if [ '$(ls -A js/min/app/en/)' ]; then rm -f js/min/app/en/*; echo 'Removed all files from js/min/app/en/'; fi
if [ '$(ls -A js/min/app/cn/)' ]; then rm -f js/min/app/cn/*; echo 'Removed all files from js/min/app/cn/'; fi
if [ '$(ls -A css/min/)' ]; then rm -f css/min/*; echo 'Removed all files from css/min/'; fi

uglifyjs -o js/min/app/cn/account-application.js js/app/cn/account-application.js && echo 'Uglified js/app/cn/account-application.js to js/min/app/cn/account-application.js';
uglifyjs -o js/min/app/cn/autochartist.js js/app/cn/autochartist.js && echo 'Uglified js/app/cn/autochartist.js to js/min/app/cn/autochartist.js';
uglifyjs -o js/min/app/cn/bank-account.js js/app/cn/bank-account.js && echo 'Uglified js/app/cn/bank-account.js to js/min/app/cn/bank-account.js';
uglifyjs -o js/min/app/cn/bank-transfer-japan.js js/app/cn/bank-transfer-japan.js && echo 'Uglified js/app/cn/bank-transfer-japan.js to js/min/app/cn/bank-transfer-japan.js';
uglifyjs -o js/min/app/cn/bank-transfer.js js/app/cn/bank-transfer.js && echo 'Uglified js/app/cn/bank-transfer.js to js/min/app/cn/bank-transfer.js';
uglifyjs -o js/min/app/cn/bank-transfer-korea.js js/app/cn/bank-transfer-korea.js && echo 'Uglified js/app/cn/bank-transfer-korea.js to js/min/app/cn/bank-transfer-korea.js';
uglifyjs -o js/min/app/cn/bank-transfer-local.js js/app/cn/bank-transfer-local.js && echo 'Uglified js/app/cn/bank-transfer-local.js to js/min/app/cn/bank-transfer-local.js';
uglifyjs -o js/min/app/cn/change-password.js js/app/cn/change-password.js && echo 'Uglified js/app/cn/change-password.js to js/min/app/cn/change-password.js';
uglifyjs -o js/min/app/cn/clientprocessreset.js js/app/cn/clientprocessreset.js && echo 'Uglified js/app/cn/clientprocessreset.js to js/min/app/cn/clientprocessreset.js';
uglifyjs -o js/min/app/cn/client-profile.js js/app/cn/client-profile.js && echo 'Uglified js/app/cn/client-profile.js to js/min/app/cn/client-profile.js';
uglifyjs -o js/min/app/cn/create-demo-confirmation.js js/app/cn/create-demo-confirmation.js && echo 'Uglified js/app/cn/create-demo-confirmation.js to js/min/app/cn/create-demo-confirmation.js';
uglifyjs -o js/min/app/cn/create-demo.js js/app/cn/create-demo.js && echo 'Uglified js/app/cn/create-demo.js to js/min/app/cn/create-demo.js';
uglifyjs -o js/min/app/cn/create-live-confirmation.js js/app/cn/create-live-confirmation.js && echo 'Uglified js/app/cn/create-live-confirmation.js to js/min/app/cn/create-live-confirmation.js';
uglifyjs -o js/min/app/cn/create-live.js js/app/cn/create-live.js && echo 'Uglified js/app/cn/create-live.js to js/min/app/cn/create-live.js';
uglifyjs -o js/min/app/cn/dashboard.js js/app/cn/dashboard.js && echo 'Uglified js/app/cn/dashboard.js to js/min/app/cn/dashboard.js';
uglifyjs -o js/min/app/cn/demoaccount.js js/app/cn/demoaccount.js && echo 'Uglified js/app/cn/demoaccount.js to js/min/app/cn/demoaccount.js';
uglifyjs -o js/min/app/cn/demo-app.js js/app/cn/demo-app.js && echo 'Uglified js/app/cn/demo-app.js to js/min/app/cn/demo-app.js';
uglifyjs -o js/min/app/cn/demo-app-result.js js/app/cn/demo-app-result.js && echo 'Uglified js/app/cn/demo-app-result.js to js/min/app/cn/demo-app-result.js';
uglifyjs -o js/min/app/cn/downloads.js js/app/cn/downloads.js && echo 'Uglified js/app/cn/downloads.js to js/min/app/cn/downloads.js';
uglifyjs -o js/min/app/cn/floating-pl.js js/app/cn/floating-pl.js && echo 'Uglified js/app/cn/floating-pl.js to js/min/app/cn/floating-pl.js';
uglifyjs -o js/min/app/cn/footer.js js/app/cn/footer.js && echo 'Uglified js/app/cn/footer.js to js/min/app/cn/footer.js';
uglifyjs -o js/min/app/cn/forgotPassword.js js/app/cn/forgotPassword.js && echo 'Uglified js/app/cn/forgotPassword.js to js/min/app/cn/forgotPassword.js';
uglifyjs -o js/min/app/cn/funding-deposit.js js/app/cn/funding-deposit.js && echo 'Uglified js/app/cn/funding-deposit.js to js/min/app/cn/funding-deposit.js';
uglifyjs -o js/min/app/cn/funding-history.js js/app/cn/funding-history.js && echo 'Uglified js/app/cn/funding-history.js to js/min/app/cn/funding-history.js';
uglifyjs -o js/min/app/cn/funding-withdraw.js js/app/cn/funding-withdraw.js && echo 'Uglified js/app/cn/funding-withdraw.js to js/min/app/cn/funding-withdraw.js';
uglifyjs -o js/min/app/cn/interaccount-confirmation.js js/app/cn/interaccount-confirmation.js && echo 'Uglified js/app/cn/interaccount-confirmation.js to js/min/app/cn/interaccount-confirmation.js';
uglifyjs -o js/min/app/cn/interaccount.js js/app/cn/interaccount.js && echo 'Uglified js/app/cn/interaccount.js to js/min/app/cn/interaccount.js';
uglifyjs -o js/min/app/cn/leftnav.js js/app/cn/leftnav.js && echo 'Uglified js/app/cn/leftnav.js to js/min/app/cn/leftnav.js';
uglifyjs -o js/min/app/cn/legal.js js/app/cn/legal.js && echo 'Uglified js/app/cn/legal.js to js/min/app/cn/legal.js';
uglifyjs -o js/min/app/cn/liveaccount.js js/app/cn/liveaccount.js && echo 'Uglified js/app/cn/liveaccount.js to js/min/app/cn/liveaccount.js';
uglifyjs -o js/min/app/cn/liveappfooter.js js/app/cn/liveappfooter.js && echo 'Uglified js/app/cn/liveappfooter.js to js/min/app/cn/liveappfooter.js';
uglifyjs -o js/min/app/cn/liveappform.js js/app/cn/liveappform.js && echo 'Uglified js/app/cn/liveappform.js to js/min/app/cn/liveappform.js';
uglifyjs -o js/min/app/cn/liveappheader.js js/app/cn/liveappheader.js && echo 'Uglified js/app/cn/liveappheader.js to js/min/app/cn/liveappheader.js';
uglifyjs -o js/min/app/cn/liveapprightrail.js js/app/cn/liveapprightrail.js && echo 'Uglified js/app/cn/liveapprightrail.js to js/min/app/cn/liveapprightrail.js';
uglifyjs -o js/min/app/cn/liveappselectlanguage.js js/app/cn/liveappselectlanguage.js && echo 'Uglified js/app/cn/liveappselectlanguage.js to js/min/app/cn/liveappselectlanguage.js';
uglifyjs -o js/min/app/cn/login.js js/app/cn/login.js && echo 'Uglified js/app/cn/login.js to js/min/app/cn/login.js';
uglifyjs -o js/min/app/cn/main.js js/app/cn/main.js && echo 'Uglified js/app/cn/main.js to js/min/app/cn/main.js';
uglifyjs -o js/min/app/cn/navbar.js js/app/cn/navbar.js && echo 'Uglified js/app/cn/navbar.js to js/min/app/cn/navbar.js';
uglifyjs -o js/min/app/cn/notification-item.js js/app/cn/notification-item.js && echo 'Uglified js/app/cn/notification-item.js to js/min/app/cn/notification-item.js';
uglifyjs -o js/min/app/cn/payment-asia.js js/app/cn/payment-asia.js && echo 'Uglified js/app/cn/payment-asia.js to js/min/app/cn/payment-asia.js';
uglifyjs -o js/min/app/cn/payment-bpay.js js/app/cn/payment-bpay.js && echo 'Uglified js/app/cn/payment-bpay.js to js/min/app/cn/payment-bpay.js';
uglifyjs -o js/min/app/cn/payment-cc.js js/app/cn/payment-cc.js && echo 'Uglified js/app/cn/payment-cc.js to js/min/app/cn/payment-cc.js';
uglifyjs -o js/min/app/cn/payment-cc-result.js js/app/cn/payment-cc-result.js && echo 'Uglified js/app/cn/payment-cc-result.js to js/min/app/cn/payment-cc-result.js';
uglifyjs -o js/min/app/cn/payment-chinaunionpay.js js/app/cn/payment-chinaunionpay.js && echo 'Uglified js/app/cn/payment-chinaunionpay.js to js/min/app/cn/payment-chinaunionpay.js';
uglifyjs -o js/min/app/cn/payment-ewallet.js js/app/cn/payment-ewallet.js && echo 'Uglified js/app/cn/payment-ewallet.js to js/min/app/cn/payment-ewallet.js';
uglifyjs -o js/min/app/cn/payment-ewallet-result.js js/app/cn/payment-ewallet-result.js && echo 'Uglified js/app/cn/payment-ewallet-result.js to js/min/app/cn/payment-ewallet-result.js';
uglifyjs -o js/min/app/cn/payment-netbanx.js js/app/cn/payment-netbanx.js && echo 'Uglified js/app/cn/payment-netbanx.js to js/min/app/cn/payment-netbanx.js';
uglifyjs -o js/min/app/cn/payment-netbanx-result.js js/app/cn/payment-netbanx-result.js && echo 'Uglified js/app/cn/payment-netbanx-result.js to js/min/app/cn/payment-netbanx-result.js';
uglifyjs -o js/min/app/cn/payment-netteller.js js/app/cn/payment-netteller.js && echo 'Uglified js/app/cn/payment-netteller.js to js/min/app/cn/payment-netteller.js';
uglifyjs -o js/min/app/cn/payment-paymentasia-2.js js/app/cn/payment-paymentasia-2.js && echo 'Uglified js/app/cn/payment-paymentasia-2.js to js/min/app/cn/payment-paymentasia-2.js';
uglifyjs -o js/min/app/cn/payment-paymentasia-result.js js/app/cn/payment-paymentasia-result.js && echo 'Uglified js/app/cn/payment-paymentasia-result.js to js/min/app/cn/payment-paymentasia-result.js';
uglifyjs -o js/min/app/cn/ransquawk.js js/app/cn/ransquawk.js && echo 'Uglified js/app/cn/ransquawk.js to js/min/app/cn/ransquawk.js';
uglifyjs -o js/min/app/cn/registration.js js/app/cn/registration.js && echo 'Uglified js/app/cn/registration.js to js/min/app/cn/registration.js';
uglifyjs -o js/min/app/cn/reset-password.js js/app/cn/reset-password.js && echo 'Uglified js/app/cn/reset-password.js to js/min/app/cn/reset-password.js';
uglifyjs -o js/min/app/cn/reutersnews.js js/app/cn/reutersnews.js && echo 'Uglified js/app/cn/reutersnews.js to js/min/app/cn/reutersnews.js';
uglifyjs -o js/min/app/cn/tfxvps.js js/app/cn/tfxvps.js && echo 'Uglified js/app/cn/tfxvps.js to js/min/app/cn/tfxvps.js';
uglifyjs -o js/min/app/cn/upload-document.js js/app/cn/upload-document.js && echo 'Uglified js/app/cn/upload-document.js to js/min/app/cn/upload-document.js';
uglifyjs -o js/min/app/en/account-application.js js/app/en/account-application.js && echo 'Uglified js/app/en/account-application.js to js/min/app/en/account-application.js';
uglifyjs -o js/min/app/en/autochartist.js js/app/en/autochartist.js && echo 'Uglified js/app/en/autochartist.js to js/min/app/en/autochartist.js';
uglifyjs -o js/min/app/en/bank-account.js js/app/en/bank-account.js && echo 'Uglified js/app/en/bank-account.js to js/min/app/en/bank-account.js';
uglifyjs -o js/min/app/en/bank-transfer-japan.js js/app/en/bank-transfer-japan.js && echo 'Uglified js/app/en/bank-transfer-japan.js to js/min/app/en/bank-transfer-japan.js';
uglifyjs -o js/min/app/en/bank-transfer.js js/app/en/bank-transfer.js && echo 'Uglified js/app/en/bank-transfer.js to js/min/app/en/bank-transfer.js';
uglifyjs -o js/min/app/en/bank-transfer-korea.js js/app/en/bank-transfer-korea.js && echo 'Uglified js/app/en/bank-transfer-korea.js to js/min/app/en/bank-transfer-korea.js';
uglifyjs -o js/min/app/en/bank-transfer-local.js js/app/en/bank-transfer-local.js && echo 'Uglified js/app/en/bank-transfer-local.js to js/min/app/en/bank-transfer-local.js';
uglifyjs -o js/min/app/en/change-password.js js/app/en/change-password.js && echo 'Uglified js/app/en/change-password.js to js/min/app/en/change-password.js';
uglifyjs -o js/min/app/en/clientprocessreset.js js/app/en/clientprocessreset.js && echo 'Uglified js/app/en/clientprocessreset.js to js/min/app/en/clientprocessreset.js';
uglifyjs -o js/min/app/en/client-profile.js js/app/en/client-profile.js && echo 'Uglified js/app/en/client-profile.js to js/min/app/en/client-profile.js';
uglifyjs -o js/min/app/en/create-demo-confirmation.js js/app/en/create-demo-confirmation.js && echo 'Uglified js/app/en/create-demo-confirmation.js to js/min/app/en/create-demo-confirmation.js';
uglifyjs -o js/min/app/en/create-demo.js js/app/en/create-demo.js && echo 'Uglified js/app/en/create-demo.js to js/min/app/en/create-demo.js';
uglifyjs -o js/min/app/en/create-live-confirmation.js js/app/en/create-live-confirmation.js && echo 'Uglified js/app/en/create-live-confirmation.js to js/min/app/en/create-live-confirmation.js';
uglifyjs -o js/min/app/en/create-live.js js/app/en/create-live.js && echo 'Uglified js/app/en/create-live.js to js/min/app/en/create-live.js';
uglifyjs -o js/min/app/en/dashboard.js js/app/en/dashboard.js && echo 'Uglified js/app/en/dashboard.js to js/min/app/en/dashboard.js';
uglifyjs -o js/min/app/en/demoaccount.js js/app/en/demoaccount.js && echo 'Uglified js/app/en/demoaccount.js to js/min/app/en/demoaccount.js';
uglifyjs -o js/min/app/en/demo-app-ib.js js/app/en/demo-app-ib.js && echo 'Uglified js/app/en/demo-app-ib.js to js/min/app/en/demo-app-ib.js';
uglifyjs -o js/min/app/en/demo-app.js js/app/en/demo-app.js && echo 'Uglified js/app/en/demo-app.js to js/min/app/en/demo-app.js';
uglifyjs -o js/min/app/en/demo-app-result.js js/app/en/demo-app-result.js && echo 'Uglified js/app/en/demo-app-result.js to js/min/app/en/demo-app-result.js';
uglifyjs -o js/min/app/en/downloads.js js/app/en/downloads.js && echo 'Uglified js/app/en/downloads.js to js/min/app/en/downloads.js';
uglifyjs -o js/min/app/en/floating-pl.js js/app/en/floating-pl.js && echo 'Uglified js/app/en/floating-pl.js to js/min/app/en/floating-pl.js';
uglifyjs -o js/min/app/en/footer.js js/app/en/footer.js && echo 'Uglified js/app/en/footer.js to js/min/app/en/footer.js';
uglifyjs -o js/min/app/en/forgotPassword.js js/app/en/forgotPassword.js && echo 'Uglified js/app/en/forgotPassword.js to js/min/app/en/forgotPassword.js';
uglifyjs -o js/min/app/en/funding-deposit.js js/app/en/funding-deposit.js && echo 'Uglified js/app/en/funding-deposit.js to js/min/app/en/funding-deposit.js';
uglifyjs -o js/min/app/en/funding-history.js js/app/en/funding-history.js && echo 'Uglified js/app/en/funding-history.js to js/min/app/en/funding-history.js';
uglifyjs -o js/min/app/en/funding-withdraw.js js/app/en/funding-withdraw.js && echo 'Uglified js/app/en/funding-withdraw.js to js/min/app/en/funding-withdraw.js';
uglifyjs -o js/min/app/en/interaccount-confirmation.js js/app/en/interaccount-confirmation.js && echo 'Uglified js/app/en/interaccount-confirmation.js to js/min/app/en/interaccount-confirmation.js';
uglifyjs -o js/min/app/en/interaccount.js js/app/en/interaccount.js && echo 'Uglified js/app/en/interaccount.js to js/min/app/en/interaccount.js';
uglifyjs -o js/min/app/en/leftnav.js js/app/en/leftnav.js && echo 'Uglified js/app/en/leftnav.js to js/min/app/en/leftnav.js';
uglifyjs -o js/min/app/en/legal.js js/app/en/legal.js && echo 'Uglified js/app/en/legal.js to js/min/app/en/legal.js';
uglifyjs -o js/min/app/en/liveaccount.js js/app/en/liveaccount.js && echo 'Uglified js/app/en/liveaccount.js to js/min/app/en/liveaccount.js';
uglifyjs -o js/min/app/en/liveappfooter.js js/app/en/liveappfooter.js && echo 'Uglified js/app/en/liveappfooter.js to js/min/app/en/liveappfooter.js';
uglifyjs -o js/min/app/en/liveappform.js js/app/en/liveappform.js && echo 'Uglified js/app/en/liveappform.js to js/min/app/en/liveappform.js';
uglifyjs -o js/min/app/en/liveappheader.js js/app/en/liveappheader.js && echo 'Uglified js/app/en/liveappheader.js to js/min/app/en/liveappheader.js';
uglifyjs -o js/min/app/en/liveapprightrail.js js/app/en/liveapprightrail.js && echo 'Uglified js/app/en/liveapprightrail.js to js/min/app/en/liveapprightrail.js';
uglifyjs -o js/min/app/en/liveappselectlanguage.js js/app/en/liveappselectlanguage.js && echo 'Uglified js/app/en/liveappselectlanguage.js to js/min/app/en/liveappselectlanguage.js';
uglifyjs -o js/min/app/en/login-alt.js js/app/en/login-alt.js && echo 'Uglified js/app/en/login-alt.js to js/min/app/en/login-alt.js';
uglifyjs -o js/min/app/en/login.js js/app/en/login.js && echo 'Uglified js/app/en/login.js to js/min/app/en/login.js';
uglifyjs -o js/min/app/en/main.js js/app/en/main.js && echo 'Uglified js/app/en/main.js to js/min/app/en/main.js';
uglifyjs -o js/min/app/en/navbar.js js/app/en/navbar.js && echo 'Uglified js/app/en/navbar.js to js/min/app/en/navbar.js';
uglifyjs -o js/min/app/en/notification-item.js js/app/en/notification-item.js && echo 'Uglified js/app/en/notification-item.js to js/min/app/en/notification-item.js';
uglifyjs -o js/min/app/en/payment-asia.js js/app/en/payment-asia.js && echo 'Uglified js/app/en/payment-asia.js to js/min/app/en/payment-asia.js';
uglifyjs -o js/min/app/en/payment-bpay.js js/app/en/payment-bpay.js && echo 'Uglified js/app/en/payment-bpay.js to js/min/app/en/payment-bpay.js';
uglifyjs -o js/min/app/en/payment-cc.js js/app/en/payment-cc.js && echo 'Uglified js/app/en/payment-cc.js to js/min/app/en/payment-cc.js';
uglifyjs -o js/min/app/en/payment-cc-result.js js/app/en/payment-cc-result.js && echo 'Uglified js/app/en/payment-cc-result.js to js/min/app/en/payment-cc-result.js';
uglifyjs -o js/min/app/en/payment-chinaunionpay.js js/app/en/payment-chinaunionpay.js && echo 'Uglified js/app/en/payment-chinaunionpay.js to js/min/app/en/payment-chinaunionpay.js';
uglifyjs -o js/min/app/en/payment-ewallet.js js/app/en/payment-ewallet.js && echo 'Uglified js/app/en/payment-ewallet.js to js/min/app/en/payment-ewallet.js';
uglifyjs -o js/min/app/en/payment-ewallet-result.js js/app/en/payment-ewallet-result.js && echo 'Uglified js/app/en/payment-ewallet-result.js to js/min/app/en/payment-ewallet-result.js';
uglifyjs -o js/min/app/en/payment-netbanx.js js/app/en/payment-netbanx.js && echo 'Uglified js/app/en/payment-netbanx.js to js/min/app/en/payment-netbanx.js';
uglifyjs -o js/min/app/en/payment-netbanx-result.js js/app/en/payment-netbanx-result.js && echo 'Uglified js/app/en/payment-netbanx-result.js to js/min/app/en/payment-netbanx-result.js';
uglifyjs -o js/min/app/en/payment-netteller.js js/app/en/payment-netteller.js && echo 'Uglified js/app/en/payment-netteller.js to js/min/app/en/payment-netteller.js';
uglifyjs -o js/min/app/en/payment-paymentasia-2.js js/app/en/payment-paymentasia-2.js && echo 'Uglified js/app/en/payment-paymentasia-2.js to js/min/app/en/payment-paymentasia-2.js';
uglifyjs -o js/min/app/en/payment-paymentasia-result.js js/app/en/payment-paymentasia-result.js && echo 'Uglified js/app/en/payment-paymentasia-result.js to js/min/app/en/payment-paymentasia-result.js';
uglifyjs -o js/min/app/en/ransquawk.js js/app/en/ransquawk.js && echo 'Uglified js/app/en/ransquawk.js to js/min/app/en/ransquawk.js';
uglifyjs -o js/min/app/en/registration.js js/app/en/registration.js && echo 'Uglified js/app/en/registration.js to js/min/app/en/registration.js';
uglifyjs -o js/min/app/en/reset-password.js js/app/en/reset-password.js && echo 'Uglified js/app/en/reset-password.js to js/min/app/en/reset-password.js';
uglifyjs -o js/min/app/en/reutersnews.js js/app/en/reutersnews.js && echo 'Uglified js/app/en/reutersnews.js to js/min/app/en/reutersnews.js';
uglifyjs -o js/min/app/en/tfxvps.js js/app/en/tfxvps.js && echo 'Uglified js/app/en/tfxvps.js to js/min/app/en/tfxvps.js';
uglifyjs -o js/min/app/en/upload-document.js js/app/en/upload-document.js && echo 'Uglified js/app/en/upload-document.js to js/min/app/en/upload-document.js';
uglifyjs -o js/min/app/jp/account-application.js js/app/jp/account-application.js && echo 'Uglified js/app/jp/account-application.js to js/min/app/jp/account-application.js';
uglifyjs -o js/min/app/jp/autochartist.js js/app/jp/autochartist.js && echo 'Uglified js/app/jp/autochartist.js to js/app/min/jp/autochartist.js';
uglifyjs -o js/min/app/jp/bank-account.js js/app/jp/bank-account.js && echo 'Uglified js/app/jp/bank-account.js to js/min/app/jp/bank-account.js';
uglifyjs -o js/min/app/jp/bank-transfer-japan.js js/app/jp/bank-transfer-japan.js && echo 'Uglified js/app/jp/bank-transfer-japan.js to js/min/app/jp/bank-transfer-japan.js';
uglifyjs -o js/min/app/jp/bank-transfer.js js/app/jp/bank-transfer.js && echo 'Uglified js/app/jp/bank-transfer.js to js/min/app/jp/bank-transfer.js';
uglifyjs -o js/min/app/jp/bank-transfer-korea.js js/app/jp/bank-transfer-korea.js && echo 'Uglified js/app/jp/bank-transfer-korea.js to js/min/app/jp/bank-transfer-korea.js';
uglifyjs -o js/min/app/jp/bank-transfer-local.js js/app/jp/bank-transfer-local.js && echo 'Uglified js/app/jp/bank-transfer-local.js to js/min/app/jp/bank-transfer-local.js';
uglifyjs -o js/min/app/jp/change-password.js js/app/jp/change-password.js && echo 'Uglified js/app/jp/change-password.js to js/min/app/jp/change-password.js';
uglifyjs -o js/min/app/jp/clientprocessreset.js js/app/jp/clientprocessreset.js && echo 'Uglified js/app/jp/clientprocessreset.js to js/min/app/jp/clientprocessreset.js';
uglifyjs -o js/min/app/jp/client-profile.js js/app/jp/client-profile.js && echo 'Uglified js/app/jp/client-profile.js to js/min/app/jp/client-profile.js';
uglifyjs -o js/min/app/jp/create-demo-confirmation.js js/app/jp/create-demo-confirmation.js && echo 'Uglified js/app/jp/create-demo-confirmation.js to js/min/app/jp/create-demo-confirmation.js';
uglifyjs -o js/min/app/jp/create-demo.js js/app/jp/create-demo.js && echo 'Uglified js/app/jp/create-demo.js to js/min/app/jp/create-demo.js';
uglifyjs -o js/min/app/jp/create-live-confirmation.js js/app/jp/create-live-confirmation.js && echo 'Uglified js/app/jp/create-live-confirmation.js to js/min/app/jp/create-live-confirmation.js';
uglifyjs -o js/min/app/jp/create-live.js js/app/jp/create-live.js && echo 'Uglified js/app/jp/create-live.js to js/min/app/jp/create-live.js';
uglifyjs -o js/min/app/jp/dashboard.js js/app/jp/dashboard.js && echo 'Uglified js/app/jp/dashboard.js to js/min/app/jp/dashboard.js';
uglifyjs -o js/min/app/jp/demoaccount.js js/app/jp/demoaccount.js && echo 'Uglified js/app/jp/demoaccount.js to js/min/app/jp/demoaccount.js';
uglifyjs -o js/min/app/jp/demo-app-ib.js js/app/jp/demo-app-ib.js && echo 'Uglified js/app/jp/demo-app-ib.js to js/min/app/jp/demo-app-ib.js';
uglifyjs -o js/min/app/jp/demo-app.js js/app/jp/demo-app.js && echo 'Uglified js/app/jp/demo-app.js to js/min/app/jp/demo-app.js';
uglifyjs -o js/min/app/jp/demo-app-result.js js/app/jp/demo-app-result.js && echo 'Uglified js/app/jp/demo-app-result.js to js/min/app/jp/demo-app-result.js';
uglifyjs -o js/min/app/jp/downloads.js js/app/jp/downloads.js && echo 'Uglified js/app/jp/downloads.js to js/min/app/jp/downloads.js';
uglifyjs -o js/min/app/jp/floating-pl.js js/app/jp/floating-pl.js && echo 'Uglified js/app/jp/floating-pl.js to js/min/app/jp/floating-pl.js';
uglifyjs -o js/min/app/jp/footer.js js/app/jp/footer.js && echo 'Uglified js/app/jp/footer.js to js/min/app/jp/footer.js';
uglifyjs -o js/min/app/jp/forgotPassword.js js/app/jp/forgotPassword.js && echo 'Uglified js/app/jp/forgotPassword.js to js/min/app/jp/forgotPassword.js';
uglifyjs -o js/min/app/jp/funding-deposit.js js/app/jp/funding-deposit.js && echo 'Uglified js/app/jp/funding-deposit.js to js/min/app/jp/funding-deposit.js';
uglifyjs -o js/min/app/jp/funding-history.js js/app/jp/funding-history.js && echo 'Uglified js/app/jp/funding-history.js to js/min/app/jp/funding-history.js';
uglifyjs -o js/min/app/jp/funding-withdraw.js js/app/jp/funding-withdraw.js && echo 'Uglified js/app/jp/funding-withdraw.js to js/min/app/jp/funding-withdraw.js';
uglifyjs -o js/min/app/jp/interaccount-confirmation.js js/app/jp/interaccount-confirmation.js && echo 'Uglified js/app/jp/interaccount-confirmation.js to js/min/app/jp/interaccount-confirmation.js';
uglifyjs -o js/min/app/jp/interaccount.js js/app/jp/interaccount.js && echo 'Uglified js/app/jp/interaccount.js to js/min/app/jp/interaccount.js';
uglifyjs -o js/min/app/jp/leftnav.js js/app/jp/leftnav.js && echo 'Uglified js/app/jp/leftnav.js to js/min/app/jp/leftnav.js';
uglifyjs -o js/min/app/jp/legal.js js/app/jp/legal.js && echo 'Uglified js/app/jp/legal.js to js/min/app/jp/legal.js';
uglifyjs -o js/min/app/jp/liveaccount.js js/app/jp/liveaccount.js && echo 'Uglified js/app/jp/liveaccount.js to js/min/app/jp/liveaccount.js';
uglifyjs -o js/min/app/jp/liveappfooter.js js/app/jp/liveappfooter.js && echo 'Uglified js/app/jp/liveappfooter.js to js/min/app/jp/liveappfooter.js';
uglifyjs -o js/min/app/jp/liveappform.js js/app/jp/liveappform.js && echo 'Uglified js/app/jp/liveappform.js to js/min/app/jp/liveappform.js';
uglifyjs -o js/min/app/jp/liveappheader.js js/app/jp/liveappheader.js && echo 'Uglified js/app/jp/liveappheader.js to js/min/app/jp/liveappheader.js';
uglifyjs -o js/min/app/jp/liveapprightrail.js js/app/jp/liveapprightrail.js && echo 'Uglified js/app/jp/liveapprightrail.js to js/min/app/jp/liveapprightrail.js';
uglifyjs -o js/min/app/jp/liveappselectlanguage.js js/app/jp/liveappselectlanguage.js && echo 'Uglified js/app/jp/liveappselectlanguage.js to js/min/app/jp/liveappselectlanguage.js';
uglifyjs -o js/min/app/jp/login.js js/app/jp/login.js && echo 'Uglified js/app/jp/login.js to js/min/app/jp/login.js';
uglifyjs -o js/min/app/jp/main.js js/app/jp/main.js && echo 'Uglified js/app/jp/main.js to js/min/app/jp/main.js';
uglifyjs -o js/min/app/jp/navbar.js js/app/jp/navbar.js && echo 'Uglified js/app/jp/navbar.js to js/min/app/jp/navbar.js';
uglifyjs -o js/min/app/jp/notification-item.js js/app/jp/notification-item.js && echo 'Uglified js/app/jp/notification-item.js to js/min/app/jp/notification-item.js';
uglifyjs -o js/min/app/jp/payment-asia.js js/app/jp/payment-asia.js && echo 'Uglified js/app/jp/payment-asia.js to js/min/app/jp/payment-asia.js';
uglifyjs -o js/min/app/jp/payment-bpay.js js/app/jp/payment-bpay.js && echo 'Uglified js/app/jp/payment-bpay.js to js/min/app/jp/payment-bpay.js';
uglifyjs -o js/min/app/jp/payment-cc.js js/app/jp/payment-cc.js && echo 'Uglified js/app/jp/payment-cc.js to js/min/app/jp/payment-cc.js';
uglifyjs -o js/min/app/jp/payment-cc-result.js js/app/jp/payment-cc-result.js && echo 'Uglified js/app/jp/payment-cc-result.js to js/min/app/jp/payment-cc-result.js';
uglifyjs -o js/min/app/jp/payment-chinaunionpay.js js/app/jp/payment-chinaunionpay.js && echo 'Uglified js/app/jp/payment-chinaunionpay.js to js/min/app/jp/payment-chinaunionpay.js';
uglifyjs -o js/min/app/jp/payment-ewallet.js js/app/jp/payment-ewallet.js && echo 'Uglified js/app/jp/payment-ewallet.js to js/min/app/jp/payment-ewallet.js';
uglifyjs -o js/min/app/jp/payment-ewallet-result.js js/app/jp/payment-ewallet-result.js && echo 'Uglified js/app/jp/payment-ewallet-result.js to js/min/app/jp/payment-ewallet-result.js';
uglifyjs -o js/min/app/jp/payment-netbanx.js js/app/jp/payment-netbanx.js && echo 'Uglified js/app/jp/payment-netbanx.js to js/min/app/jp/payment-netbanx.js';
uglifyjs -o js/min/app/jp/payment-netbanx-result.js js/app/jp/payment-netbanx-result.js && echo 'Uglified js/app/jp/payment-netbanx-result.js to js/min/app/jp/payment-netbanx-result.js';
uglifyjs -o js/min/app/jp/payment-netteller.js js/app/jp/payment-netteller.js && echo 'Uglified js/app/jp/payment-netteller.js to js/min/app/jp/payment-netteller.js';
uglifyjs -o js/min/app/jp/payment-paymentasia-2.js js/app/jp/payment-paymentasia-2.js && echo 'Uglified js/app/jp/payment-paymentasia-2.js to js/min/app/jp/payment-paymentasia-2.js';
uglifyjs -o js/min/app/jp/payment-paymentasia-result.js js/app/jp/payment-paymentasia-result.js && echo 'Uglified js/app/jp/payment-paymentasia-result.js to js/min/app/jp/payment-paymentasia-result.js';
uglifyjs -o js/min/app/jp/ransquawk.js js/app/jp/ransquawk.js && echo 'Uglified js/app/jp/ransquawk.js to js/min/app/jp/ransquawk.js';
uglifyjs -o js/min/app/jp/registration.js js/app/jp/registration.js && echo 'Uglified js/app/jp/registration.js to js/min/app/jp/registration.js';
uglifyjs -o js/min/app/jp/reset-password.js js/app/jp/reset-password.js && echo 'Uglified js/app/jp/reset-password.js to js/min/app/jp/reset-password.js';
uglifyjs -o js/min/app/jp/reutersnews.js js/app/jp/reutersnews.js && echo 'Uglified js/app/jp/reutersnews.js to js/min/app/jp/reutersnews.js';
uglifyjs -o js/min/app/jp/tfxvps.js js/app/jp/tfxvps.js && echo 'Uglified js/app/jp/tfxvps.js to js/min/app/jp/tfxvps.js';
uglifyjs -o js/min/app/jp/upload-document.js js/app/jp/upload-document.js && echo 'Uglified js/app/jp/upload-document.js to js/min/app/jp/upload-document.js';
uglifyjs -o js/min/bootstrap/cn/browserredirect-main.js js/bootstrap/cn/browserredirect-main.js && echo 'Uglified js/bootstrap/cn/browserredirect-main.js to js/min/bootstrap/cn/browserredirect-main.js';
uglifyjs -o js/min/bootstrap/cn/clientprocessreset-main.js js/bootstrap/cn/clientprocessreset-main.js && echo 'Uglified js/bootstrap/cn/clientprocessreset-main.js to js/min/bootstrap/cn/clientprocessreset-main.js';
uglifyjs -o js/min/bootstrap/cn/demo-app-landing-main.js js/bootstrap/cn/demo-app-landing-main.js && echo 'Uglified js/bootstrap/cn/demo-app-landing-main.js to js/min/bootstrap/cn/demo-app-landing-main.js';
uglifyjs -o js/min/bootstrap/cn/demo-app-main.js js/bootstrap/cn/demo-app-main.js && echo 'Uglified js/bootstrap/cn/demo-app-main.js to js/min/bootstrap/cn/demo-app-main.js';
uglifyjs -o js/min/bootstrap/cn/demo-app-result-main.js js/bootstrap/cn/demo-app-result-main.js && echo 'Uglified js/bootstrap/cn/demo-app-result-main.js to js/min/bootstrap/cn/demo-app-result-main.js';
uglifyjs -o js/min/bootstrap/cn/downloads-main.js js/bootstrap/cn/downloads-main.js && echo 'Uglified js/bootstrap/cn/downloads-main.js to js/min/bootstrap/cn/downloads-main.js';
uglifyjs -o js/min/bootstrap/cn/funding-banktransfer-japan-main.js js/bootstrap/cn/funding-banktransfer-japan-main.js && echo 'Uglified js/bootstrap/cn/funding-banktransfer-japan-main.js to js/min/bootstrap/cn/funding-banktransfer-japan-main.js';
uglifyjs -o js/min/bootstrap/cn/funding-banktransfer-main.js js/bootstrap/cn/funding-banktransfer-main.js && echo 'Uglified js/bootstrap/cn/funding-banktransfer-main.js to js/min/bootstrap/cn/funding-banktransfer-main.js';
uglifyjs -o js/min/bootstrap/cn/funding-withdraw-main.js js/bootstrap/cn/funding-withdraw-main.js && echo 'Uglified js/bootstrap/cn/funding-withdraw-main.js to js/min/bootstrap/cn/funding-withdraw-main.js';
uglifyjs -o js/min/bootstrap/cn/livechat.js js/bootstrap/cn/livechat.js && echo 'Uglified js/bootstrap/cn/livechat.js to js/min/bootstrap/cn/livechat.js';
uglifyjs -o js/min/bootstrap/cn/login-main.js js/bootstrap/cn/login-main.js && echo 'Uglified js/bootstrap/cn/login-main.js to js/min/bootstrap/cn/login-main.js';
uglifyjs -o js/min/bootstrap/cn/main-main.js js/bootstrap/cn/main-main.js && echo 'Uglified js/bootstrap/cn/main-main.js to js/min/bootstrap/cn/main-main.js';
uglifyjs -o js/min/bootstrap/cn/payment-cc-result-main.js js/bootstrap/cn/payment-cc-result-main.js && echo 'Uglified js/bootstrap/cn/payment-cc-result-main.js to js/min/bootstrap/cn/payment-cc-result-main.js';
uglifyjs -o js/min/bootstrap/cn/payment-ewallet-result-main.js js/bootstrap/cn/payment-ewallet-result-main.js && echo 'Uglified js/bootstrap/cn/payment-ewallet-result-main.js to js/min/bootstrap/cn/payment-ewallet-result-main.js';
uglifyjs -o js/min/bootstrap/cn/payment-netbanx-result-main.js js/bootstrap/cn/payment-netbanx-result-main.js && echo 'Uglified js/bootstrap/cn/payment-netbanx-result-main.js to js/min/bootstrap/cn/payment-netbanx-result-main.js';
uglifyjs -o js/min/bootstrap/cn/payment-paymentasia-result-main.js js/bootstrap/cn/payment-paymentasia-result-main.js && echo 'Uglified js/bootstrap/cn/payment-paymentasia-result-main.js to js/min/bootstrap/cn/payment-paymentasia-result-main.js';
uglifyjs -o js/min/bootstrap/cn/reset-password-main.js js/bootstrap/cn/reset-password-main.js && echo 'Uglified js/bootstrap/cn/reset-password-main.js to js/min/bootstrap/cn/reset-password-main.js';
uglifyjs -o js/min/bootstrap/cn/support-main.js js/bootstrap/cn/support-main.js && echo 'Uglified js/bootstrap/cn/support-main.js to js/min/bootstrap/cn/support-main.js';
uglifyjs -o js/min/bootstrap/en/browserredirect-main.js js/bootstrap/en/browserredirect-main.js && echo 'Uglified js/bootstrap/en/browserredirect-main.js to js/min/bootstrap/en/browserredirect-main.js';
uglifyjs -o js/min/bootstrap/en/clientprocessreset-main.js js/bootstrap/en/clientprocessreset-main.js && echo 'Uglified js/bootstrap/en/clientprocessreset-main.js to js/min/bootstrap/en/clientprocessreset-main.js';
uglifyjs -o js/min/bootstrap/en/clientprocessreset-new.js js/bootstrap/en/clientprocessreset-new.js && echo 'Uglified js/bootstrap/en/clientprocessreset-new.js to js/min/bootstrap/en/clientprocessreset-new.js';
uglifyjs -o js/min/bootstrap/en/demo-app-landing-ib-main.js js/bootstrap/en/demo-app-landing-ib-main.js && echo 'Uglified js/bootstrap/en/demo-app-landing-ib-main.js to js/min/bootstrap/en/demo-app-landing-ib-main.js';
uglifyjs -o js/min/bootstrap/en/demo-app-landing-main.js js/bootstrap/en/demo-app-landing-main.js && echo 'Uglified js/bootstrap/en/demo-app-landing-main.js to js/min/bootstrap/en/demo-app-landing-main.js';
uglifyjs -o js/min/bootstrap/en/demo-app-main.js js/bootstrap/en/demo-app-main.js && echo 'Uglified js/bootstrap/en/demo-app-main.js to js/min/bootstrap/en/demo-app-main.js';
uglifyjs -o js/min/bootstrap/en/demo-app-result-main.js js/bootstrap/en/demo-app-result-main.js && echo 'Uglified js/bootstrap/en/demo-app-result-main.js to js/min/bootstrap/en/demo-app-result-main.js';
uglifyjs -o js/min/bootstrap/en/downloads-main.js js/bootstrap/en/downloads-main.js && echo 'Uglified js/bootstrap/en/downloads-main.js to js/min/bootstrap/en/downloads-main.js';
uglifyjs -o js/min/bootstrap/en/funding-banktransfer-japan-main.js js/bootstrap/en/funding-banktransfer-japan-main.js && echo 'Uglified js/bootstrap/en/funding-banktransfer-japan-main.js to js/min/bootstrap/en/funding-banktransfer-japan-main.js';
uglifyjs -o js/min/bootstrap/en/funding-banktransfer-main.js js/bootstrap/en/funding-banktransfer-main.js && echo 'Uglified js/bootstrap/en/funding-banktransfer-main.js to .js/min/bootstrap/en/funding-banktransfer-mainjs';
uglifyjs -o js/min/bootstrap/en/funding-withdraw-main.js js/bootstrap/en/funding-withdraw-main.js && echo 'Uglified js/bootstrap/en/funding-withdraw-main.js to js/min/bootstrap/en/funding-withdraw-main.js';
uglifyjs -o js/min/bootstrap/en/livechat.js js/bootstrap/en/livechat.js && echo 'Uglified js/bootstrap/en/livechat.js to js/min/bootstrap/en/livechat.js';
uglifyjs -o js/min/bootstrap/en/login-alt-main.js js/bootstrap/en/login-alt-main.js && echo 'Uglified js/bootstrap/en/login-alt-main.js to js/min/bootstrap/en/login-alt-main.js';
uglifyjs -o js/min/bootstrap/en/login-main.js js/bootstrap/en/login-main.js && echo 'Uglified js/bootstrap/en/login-main.js to js/min/bootstrap/en/login-main.js';
uglifyjs -o js/min/bootstrap/en/main-main.js js/bootstrap/en/main-main.js && echo 'Uglified js/bootstrap/en/main-main.js to js/min/bootstrap/en/main-main.js';
uglifyjs -o js/min/bootstrap/en/payment-cc-result-main.js js/bootstrap/en/payment-cc-result-main.js && echo 'Uglified js/bootstrap/en/payment-cc-result-main.js to js/min/bootstrap/en/payment-cc-result-main.js';
uglifyjs -o js/min/bootstrap/en/payment-ewallet-result-main.js js/bootstrap/en/payment-ewallet-result-main.js && echo 'Uglified js/bootstrap/en/payment-ewallet-result-main.js to js/min/bootstrap/en/payment-ewallet-result-main.js';
uglifyjs -o js/min/bootstrap/en/payment-netbanx-result-main.js js/bootstrap/en/payment-netbanx-result-main.js && echo 'Uglified js/bootstrap/en/payment-netbanx-result-main.js to js/min/bootstrap/en/payment-netbanx-result-main.js';
uglifyjs -o js/min/bootstrap/en/payment-paymentasia-2-main.js js/bootstrap/en/payment-paymentasia-2-main.js && echo 'Uglified js/bootstrap/en/payment-paymentasia-2-main.js to js/min/bootstrap/en/payment-paymentasia-2-main.js';
uglifyjs -o js/min/bootstrap/en/payment-paymentasia-result-main.js js/bootstrap/en/payment-paymentasia-result-main.js && echo 'Uglified js/bootstrap/en/payment-paymentasia-result-main.js to js/min/bootstrap/en/payment-paymentasia-result-main.js';
uglifyjs -o js/min/bootstrap/en/reset-password-main.js js/bootstrap/en/reset-password-main.js && echo 'Uglified js/bootstrap/en/resetpassword-main.js to js/min/bootstrap/en/resetpassword-main.js';
uglifyjs -o js/min/bootstrap/en/resetpassword-main.js js/bootstrap/en/resetpassword-main.js && echo 'Uglified js/bootstrap/en/resetpassword-main.js to js/min/bootstrap/en/resetpassword-main.js';
uglifyjs -o js/min/bootstrap/en/support-main.js js/bootstrap/en/support-main.js && echo 'Uglified js/bootstrap/en/support-main.js to js/min/bootstrap/en/support-main.js';
uglifyjs -o js/min/bootstrap/jp/browserredirect-main.js js/bootstrap/jp/browserredirect-main.js && echo 'Uglified js/bootstrap/jp/browserredirect-main.js to js/min/bootstrap/jp/browserredirect-main.js';
uglifyjs -o js/min/bootstrap/jp/clientprocessreset-main.js js/bootstrap/jp/clientprocessreset-main.js && echo 'Uglified js/bootstrap/jp/clientprocessreset-main.js to js/min/bootstrap/jp/clientprocessreset-main.js';
uglifyjs -o js/min/bootstrap/jp/demo-app-landing-ib-main.js js/bootstrap/jp/demo-app-landing-ib-main.js && echo 'Uglified js/bootstrap/jp/demo-app-landing-ib-main.js to js/min/bootstrap/jp/demo-app-landing-ib-main.js';
uglifyjs -o js/min/bootstrap/jp/demo-app-landing-main.js js/bootstrap/jp/demo-app-landing-main.js && echo 'Uglified js/bootstrap/jp/demo-app-landing-main.js to js/min/bootstrap/jp/demo-app-landing-main.js';
uglifyjs -o js/min/bootstrap/jp/demo-app-main.js js/bootstrap/jp/demo-app-main.js && echo 'Uglified js/bootstrap/jp/demo-app-main.js to js/min/bootstrap/jp/demo-app-main.js.js';
uglifyjs -o js/min/bootstrap/jp/demo-app-result-main.js js/bootstrap/jp/demo-app-result-main.js && echo 'Uglified js/bootstrap/jp/demo-app-result-main.js to js/min/bootstrap/jp/demo-app-result-main.js';
uglifyjs -o js/min/bootstrap/jp/downloads-main.js js/bootstrap/jp/downloads-main.js && echo 'Uglified js/bootstrap/jp/downloads-main.js to js/min/bootstrap/jp/downloads-main.js';
uglifyjs -o js/min/bootstrap/jp/funding-banktransfer-japan-main.js js/bootstrap/jp/funding-banktransfer-japan-main.js && echo 'Uglified js/bootstrap/jp/funding-banktransfer-japan-main.js to js/min/bootstrap/jp/funding-banktransfer-japan-main.js';
uglifyjs -o js/min/bootstrap/jp/funding-banktransfer-main.js js/bootstrap/jp/funding-banktransfer-main.js && echo 'Uglified js/bootstrap/jp/funding-banktransfer-main.js to js/min/bootstrap/jp/funding-banktransfer-main.js';
uglifyjs -o js/min/bootstrap/jp/funding-withdraw-main.js js/bootstrap/jp/funding-withdraw-main.js && echo 'Uglified js/bootstrap/jp/funding-withdraw-main.js to js/min/bootstrap/jp/funding-withdraw-main.js';
uglifyjs -o js/min/bootstrap/jp/livechat.js js/bootstrap/jp/livechat.js && echo 'Uglified js/bootstrap/jp/livechat.js to js/min/bootstrap/jp/livechat.js';
uglifyjs -o js/min/bootstrap/jp/login-main.js js/bootstrap/jp/login-main.js && echo 'Uglified js/bootstrap/jp/login-main.js to js/min/bootstrap/jp/login-main.js';
uglifyjs -o js/min/bootstrap/jp/main-main.js js/bootstrap/jp/main-main.js && echo 'Uglified js/bootstrap/jp/main-main.js to js/min/bootstrap/jp/main-main.js';
uglifyjs -o js/min/bootstrap/jp/payment-cc-result-main.js js/bootstrap/jp/payment-cc-result-main.js && echo 'Uglified js/bootstrap/jp/payment-cc-result-main.js to js/min/bootstrap/jp/payment-cc-result-main.js';
uglifyjs -o js/min/bootstrap/jp/payment-ewallet-result-main.js js/bootstrap/jp/payment-ewallet-result-main.js && echo 'Uglified js/bootstrap/jp/payment-ewallet-result-main.js to js/min/bootstrap/jp/payment-ewallet-result-main.js';
uglifyjs -o js/min/bootstrap/jp/payment-netbanx-result-main.js js/bootstrap/jp/payment-netbanx-result-main.js && echo 'Uglified js/bootstrap/jp/payment-netbanx-result-main.js to js/min/bootstrap/jp/payment-netbanx-result-main.js';
uglifyjs -o js/min/bootstrap/jp/payment-paymentasia-result-main.js js/bootstrap/jp/payment-paymentasia-result-main.js && echo 'Uglified js/bootstrap/jp/payment-paymentasia-result-main.js to js/min/bootstrap/jp/payment-paymentasia-result-main.js';
uglifyjs -o js/min/bootstrap/jp/reset-password-main.js js/bootstrap/jp/reset-password-main.js && echo 'Uglified js/bootstrap/jp/reset-password-main.js to min/bootstrap/jp/reset-password-main.js';
uglifyjs -o js/min/bootstrap/jp/support-main.js js/bootstrap/jp/support-main.js && echo 'Uglified js/bootstrap/jp/support-main.js to js/min/bootstrap/jp/support-main.js';
uglifyjs -o js/min/models/cn/request.js js/models/cn/request.js && echo 'Uglified js/models/cn/request.js to min/models/cn/request.js';
uglifyjs -o js/min/models/en/request.js js/models/en/request.js && echo 'Uglified js/models/en/request.js to min/models/en/request.js';
uglifyjs -o js/min/models/jp/request.js js/models/jp/request.js && echo 'Uglified js/models/jp/request.js to min/models/jp/request.js';
uglifyjs -o js/min/utils/parsley-custom-validators.js js/utils/parsley-custom-validators.js && echo 'Uglified js/utils/parsley-custom-validators.js to js/min/utils/parsley-custom-validators.js';
uglifyjs -o js/min/utils/payment-utils.js js/utils/payment-utils.js && echo 'Uglified js/utils/payment-utils.js to js/min/utils/payment-utils.js';
uglifyjs -o js/min/utils/testIE.js js/utils/testIE.js && echo 'Uglified js/utils/testIE.js to js/min/utils/testIE.js';
uglifyjs -o js/min/utils/utils.js js/utils/utils.js && echo 'Uglified js/utils/utils.js to js/min/utils/utils.js';
uglifyjs -o js/min/viewmodels/account.js js/viewmodels/account.js && echo 'Uglified js/viewmodels/account.js to js/min/viewmodels/account.js';
uglifyjs -o js/min/viewmodels/accountapplication.js js/viewmodels/accountapplication.js && echo 'Uglified js/viewmodels/accountapplication.js to js/min/viewmodels/accountapplication.js';
uglifyjs -o js/min/viewmodels/accountbalance.js js/viewmodels/accountbalance.js && echo 'Uglified js/viewmodels/accountbalance.js to js/min/viewmodels/accountbalance.js';
uglifyjs -o js/min/viewmodels/autochartist.js js/viewmodels/autochartist.js && echo 'Uglified js/viewmodels/autochartist.js to js/min/viewmodels/autochartist.js';
uglifyjs -o js/min/viewmodels/availablebankaccounts.js js/viewmodels/availablebankaccounts.js && echo 'Uglified js/viewmodels/availablebankaccounts.js to js/min/viewmodels/availablebankaccounts.js';
uglifyjs -o js/min/viewmodels/bankaccounts.js js/viewmodels/bankaccounts.js && echo 'Uglified js/viewmodels/bankaccounts.js to js/min/viewmodels/bankaccounts.js';
uglifyjs -o js/min/viewmodels/banktransfer.js js/viewmodels/banktransfer.js && echo 'Uglified js/viewmodels/banktransfer.js to js/min/viewmodels/banktransfer.js';
uglifyjs -o js/min/viewmodels/banktransferjapan.js js/viewmodels/banktransferjapan.js && echo 'Uglified js/viewmodels/banktransferjapan.js to js/min/viewmodels/banktransferjapan.js';
uglifyjs -o js/min/viewmodels/banktransferkorea.js js/viewmodels/banktransferkorea.js && echo 'Uglified js/viewmodels/banktransferkorea.js to js/min/viewmodels/banktransferkorea.js';
uglifyjs -o js/min/viewmodels/banktransferlocal.js js/viewmodels/banktransferlocal.js && echo 'Uglified js/viewmodels/banktransferlocal.js to js/min/viewmodels/banktransferlocal.js';
uglifyjs -o js/min/viewmodels/breadcrumb.js js/viewmodels/breadcrumb.js && echo 'Uglified js/viewmodels/breadcrumb.js to js/min/viewmodels/breadcrumb.js';
uglifyjs -o js/min/viewmodels/changepassword.js js/viewmodels/changepassword.js && echo 'Uglified js/viewmodels/changepassword.js to js/min/viewmodels/changepassword.js';
uglifyjs -o js/min/viewmodels/clientprofile.js js/viewmodels/clientprofile.js && echo 'Uglified js/viewmodels/clientprofile.js to js/min/viewmodels/clientprofile.js.js';
uglifyjs -o js/min/viewmodels/create-demo-confirmation.js js/viewmodels/create-demo-confirmation.js && echo 'Uglified js/viewmodels/create-demo-confirmation.js to js/min/viewmodels/create-demo-confirmation.js';
uglifyjs -o js/min/viewmodels/create-demo.js js/viewmodels/create-demo.js && echo 'Uglified js/viewmodels/create-demo.js to js/min/viewmodels/create-demo.js';
uglifyjs -o js/min/viewmodels/create-live-confirmation.js js/viewmodels/create-live-confirmation.js && echo 'Uglified js/viewmodels/create-live-confirmation.js to js/min/viewmodels/create-live-confirmation.js';
uglifyjs -o js/min/viewmodels/create-live.js js/viewmodels/create-live.js && echo 'Uglified js/viewmodels/create-live.js to js/min/viewmodels/create-live.js';
uglifyjs -o js/min/viewmodels/demoaccount.js js/viewmodels/demoaccount.js && echo 'Uglified js/viewmodels/demoaccount.js to js/min/viewmodels/demoaccount.js';
uglifyjs -o js/min/viewmodels/ewallets.js js/viewmodels/ewallets.js && echo 'Uglified js/viewmodels/ewallets.js to js/min/viewmodels/ewallets.js';
uglifyjs -o js/min/viewmodels/floatingpl.js js/viewmodels/floatingpl.js && echo 'Uglified js/viewmodels/floatingpl.js to js/min/viewmodels/floatingpl.js';
uglifyjs -o js/min/viewmodels/fundingwithdraw.js js/viewmodels/fundingwithdraw.js && echo 'Uglified js/viewmodels/fundingwithdraw.js to js/min/viewmodels/fundingwithdraw.js';
uglifyjs -o js/min/viewmodels/interaccountconfirmation.js js/viewmodels/interaccountconfirmation.js && echo 'Uglified js/viewmodels/interaccountconfirmation.js to js/min/viewmodels/interaccountconfirmation.js';
uglifyjs -o js/min/viewmodels/interaccountdetail.js js/viewmodels/interaccountdetail.js && echo 'Uglified js/viewmodels/interaccountdetail.js to js/min/viewmodels/interaccountdetail.js';
uglifyjs -o js/min/viewmodels/interaccount.js js/viewmodels/interaccount.js && echo 'Uglified js/viewmodels/interaccount.js to js/min/viewmodels/interaccount.js';
uglifyjs -o js/min/viewmodels/legal.js js/viewmodels/legal.js && echo 'Uglified js/viewmodels/legal.js to js/min/viewmodels/legal.js';
uglifyjs -o js/min/viewmodels/liveaccount.js js/viewmodels/liveaccount.js && echo 'Uglified js/viewmodels/liveaccount.js to js/min/viewmodels/liveaccount.js';
uglifyjs -o js/min/viewmodels/notifications.js js/viewmodels/notifications.js && echo 'Uglified js/viewmodels/notifications.js to js/min/viewmodels/notifications.js';
uglifyjs -o js/min/viewmodels/paymentasia.js js/viewmodels/paymentasia.js && echo 'Uglified js/viewmodels/paymentasia.js to js/min/viewmodels/paymentasia.js';
uglifyjs -o js/min/viewmodels/paymentbpay.js js/viewmodels/paymentbpay.js && echo 'Uglified js/viewmodels/paymentbpay.js to js/min/viewmodels/paymentbpay.js';
uglifyjs -o js/min/viewmodels/paymentcc.js js/viewmodels/paymentcc.js && echo 'Uglified js/viewmodels/paymentcc.js to js/min/viewmodels/paymentcc.js';
uglifyjs -o js/min/viewmodels/paymentchinaunionpay.js js/viewmodels/paymentchinaunionpay.js && echo 'Uglified js/viewmodels/paymentchinaunionpay.js to js/min/viewmodels/paymentchinaunionpay.js';
uglifyjs -o js/min/viewmodels/paymentewallet.js js/viewmodels/paymentewallet.js && echo 'Uglified js/viewmodels/paymentewallet.js to js/min/viewmodels/paymentewallet.js';
uglifyjs -o js/min/viewmodels/paymentnetbanx.js js/viewmodels/paymentnetbanx.js && echo 'Uglified js/viewmodels/paymentnetbanx.js to js/min/viewmodels/paymentnetbanx.js';
uglifyjs -o js/min/viewmodels/paymentnetteller.js js/viewmodels/paymentnetteller.js && echo 'Uglified js/viewmodels/paymentnetteller.js to js/min/viewmodels/paymentnetteller.js';
uglifyjs -o js/min/viewmodels/ransquawk.js js/viewmodels/ransquawk.js && echo 'Uglified js/viewmodels/ransquawk.js to js/min/viewmodels/ransquawk.js';
uglifyjs -o js/min/viewmodels/recentdeposits.js js/viewmodels/recentdeposits.js && echo 'Uglified js/viewmodels/recentdeposits.js to js/min/viewmodels/recentdeposits.js';
uglifyjs -o js/min/viewmodels/recenttransactions.js js/viewmodels/recenttransactions.js && echo 'Uglified js/viewmodels/recenttransactions.js to js/min/viewmodels/recenttransactions.js';
uglifyjs -o js/min/viewmodels/reutersnews.js js/viewmodels/reutersnews.js && echo 'Uglified js/viewmodels/reutersnews.js to js/min/viewmodels/reutersnews.js';
uglifyjs -o js/min/viewmodels/sectionheader.js js/viewmodels/sectionheader.js && echo 'Uglified js/viewmodels/sectionheader.js to js/min/viewmodels/sectionheader.js';
uglifyjs -o js/min/viewmodels/tfxvps.js js/viewmodels/tfxvps.js && echo 'Uglified js/viewmodels/tfxvps.js to js/min/viewmodels/tfxvps.js';
uglifyjs -o js/min/viewmodels/updates.js js/viewmodels/updates.js && echo 'Uglified js/viewmodels/updates.js to js/min/viewmodels/updates.js';
uglifyjs -o js/min/viewmodels/uploaddocument.js js/viewmodels/uploaddocument.js && echo 'Uglified js/viewmodels/uploaddocument.js to js/min/viewmodels/uploaddocument.js';
cp css/bootstrap-datetimepicker.min.css css/min/ && echo 'Copied css/bootstrap-datetimepicker.min.css to css/min/';
cp css/bootstrap-formhelpers.min.css css/min/ && echo 'Copied css/bootstrap-formhelpers.min.css to css/min/';
cp css/bootstrap_live_app.min.css css/min/ && echo 'Copied css/bootstrap_live_app.min.css to css/min/';
cp css/bootstrap.min.css css/min/ && echo 'Copied css/bootstrap.min.css to css/min/';
cp css/bootstrap-theme.min.css css/min/ && echo 'Copied css/bootstrap-theme.min.css to css/min/';
cp css/kendo.common.min.css css/min/ && echo 'Copied css/bootstrap-datetimepicker.min.css to css/min/';
cp css/kendo.dataviz.default.min.css css/min/ && echo 'Copied css/bootstrap-formhelpers.min.css to css/min/';
cp css/kendo.dataviz.min.css css/min/ && echo 'Copied css/bootstrap_live_app.min.css to css/min/';
cp css/kendo.default.min.css css/min/ && echo 'Copied css/bootstrap.min.css to css/min/';
cp css/kendo.default.mobile.min.css css/min/ && echo 'Copied css/bootstrap-theme.min.css to css/min/';
cp css/kendo.mobile.all.min.css css/min/ && echo 'Copied css/bootstrap.min.css to css/min/';
uglifycss css/slidemenu.css > css/min/slidemenu.css && echo 'Uglified css/slidemenu.css to css/min/slidemenu.css';
uglifycss css/style.css > css/min/style.css && echo 'Uglified css/style.css to css/min/style.css';
uglifycss css/parsley.css > css/min/parsley.css && echo 'Uglified css/parsley.css to css/min/parsley.css';
uglifycss css/flipclock.css > css/min/flipclock.css && echo 'Uglified css/flipclock.css to css/min/flipclock.css';
uglifycss css/resumable.css > css/min/resumable.css && echo 'Uglified css/resumable.css to css/min/resumable.css';
uglifycss css/select2.css > css/min/select2.css && echo 'Uglified css/select2.css to css/min/select2.css';
uglifycss css/modal.css > css/min/modal.css && echo 'Uglified css/modal.css to css/min/modal.css';
uglifycss css/login.css > css/min/login.css && echo 'Uglified css/login.css to css/min/login.css';
uglifycss css/bootstrap-combobox.css > css/min/bootstrap-combobox.css && echo 'Uglified css/bootstrap-combobox.css to css/min/bootstrap-combobox.css';
uglifycss css/cc.css > css/min/cc.css && echo 'Uglified css/cc.css to css/min/cc.css';
uglifycss css/datepicker.css > css/min/datepicker.css && echo 'Uglified css/datepicker.css to css/min/datepicker.css';
uglifycss css/demoaccount.css > css/min/demoaccount.css && echo 'Uglified css/demoaccount.css to css/min/demoaccount.css';
uglifycss css/flipclock.css > css/min/flipclock.css && echo 'Uglified css/flipclock.css to css/min/flipclock.css';
uglifycss css/globaltfx.css > css/min/globaltfx.css && echo 'Uglified css/globaltfx.css to css/min/globaltfx.css';
uglifycss css/live_app.css > css/min/live_app.css && echo 'Uglified css/live_app.css to css/min/live_app.css';
uglifycss css/portal.css > css/min/portal.css && echo 'Uglified  css/portal.css to css/min/portal.css';